"""empty message

Revision ID: 012a2d3a2f47
Revises: 9d5043f2fcf9
Create Date: 2025-11-10 04:25:30.081390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012a2d3a2f47'
down_revision: Union[str, Sequence[str], None] = '9d5043f2fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('token_expires_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_expires_at')
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
